# Generated by Django 4.1.5 on 2023-02-05 19:55

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('struct_app', '0004_alter_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='struct_app.group', verbose_name='Вышестоящее подразделение'),
        ),
    ]
