# Generated by Django 4.1.5 on 2023-02-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struct_app', '0007_alter_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='slug',
            field=models.SlugField(max_length=150, null=True),
        ),
    ]
