# Generated by Django 4.1.5 on 2023-02-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struct_app', '0011_unit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
