# Generated by Django 4.1.5 on 2023-02-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('struct_app', '0015_alter_unit_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='birthdayDate',
            new_name='birthday_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dateOfJoining',
            new_name='date_of_joining',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeName',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeePost',
            new_name='employee_post',
        ),
    ]
