# Generated by Django 4.1.5 on 2023-02-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struct_app', '0019_alter_employee_birthday_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Фамилия сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(default=None, max_length=50, verbose_name='Отчество сотрудника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя сотрудника'),
        ),
    ]
