# Generated by Django 4.1.5 on 2023-02-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('struct_app', '0021_alter_employee_employee_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='name',
        ),
    ]
