# Generated by Django 4.1.5 on 2023-02-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('struct_app', '0022_rename_employee_name_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_post',
            new_name='post',
        ),
    ]
